# Generated by Django 3.1.5 on 2021-01-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20210105_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='actual_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='actual_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='planned_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
